### ISSUE TITLE
Better testing

### ISSUE THREAD

**Issue by olimorris** [publiux/laravelcdn#15]
I don't believe mocking everything in the tests really flexes the package.

As an enchantment, I propose that integration tests should be used to:

1) Push files from a test/stubs directory to an AWS bucket and assert this has happened
2) Push again and assert that no new files were uploaded as they already exist
3) Delete files from AWS and assert the bucket is empty

Using TravisCI we should be able to store the credentials of the bucket as environment variables to stop people from using the bucket for malicious purposes.

**Comment by publiux** [comment]
AWS tests their code using mocked objects, so it's good enough for me. If an upload fails, or we can't index a bucket, etc., that's not a failure of our code, but of the called api, and error handling should be implemented accordingly in one's production code.

However, I do agree that we need a test for duplicate file detection and will write one.

**Comment by olimorris** [comment]
@publiux if I have some time over the next month I may see about creating a pull request and see if you'd be open to merging.

Either way, it's great that you're taking this project on. I helped contribute to vinelab's package but things were slow.
