### ISSUE TITLE
Unable to composer require

### ISSUE THREAD

**Issue by asahasrabuddhe** [publiux/laravelcdn#19]
Hello,

Whenever I try to install this package, I get the following error

Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing publiux/laravelcdn (2.0.0)
    Loading from cache

Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

                                                           
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Publiux\laravelcdn\CDNServiceProvider' not found  
                                                           

Script php artisan optimize handling the post-update-cmd event returned with an error

                      
  [RuntimeException]  
  Error Output:       
                      

I am using Laravel 5.5 Please help!

Regards,
Ajitem

**Comment by publiux** [comment]
Fixed by your pull request.
