### ISSUE TITLE
Class 'Cdn' not found 

### ISSUE THREAD

**Issue by paatrick** [publiux/laravelcdn#23]
Hi,

When trying to call Cdn::path() I have this problem at view

Class 'Cdn' not found 

Laravel 5.4
Homestead

**Comment by publiux** [comment]
Can you try with CDN instead of Cdn?

**Comment by paatrick** [comment]
Yes, but I still did not succeed :/

![captura de tela 2017-09-15 as 16 49 18](https://user-images.githubusercontent.com/16599542/30500741-0f2b2dde-9a36-11e7-9ffa-a345fe2fe4d5.png)

**Comment by publiux** [comment]
Which version of Laravel are you using?

**Comment by paatrick** [comment]
I using Laravel 5.4

**Comment by publiux** [comment]
Did you register the service provider and facade?

**Comment by paatrick** [comment]
I only registered the provider, according to the documentation
Publiux\laravelcdn\CdnServiceProvider::class

How do I configure the Facade ?

**Comment by publiux** [comment]
Can you try adding the following to config/app.php in the aliases array?

'CDN' => Publiux\laravelcdn\Facades\CdnFacadeAccessor::class

**Comment by paatrick** [comment]
Yes, I had added this facade, however a new error appears:
Undefined index: scheme (View: /home/vagrant/Projects/myproject.com/resources/views/home/index.blade.php)

![captura de tela 2017-09-15 as 17 49 55](https://user-images.githubusercontent.com/16599542/30502923-9ce7d192-9a3e-11e7-92ba-cd606482b98a.png)

**Comment by publiux** [comment]
Can you tell me what you have set as your CDN_Url in your .env file? Alternatively, you may have specified it in the config/cdn.php file (you did remember to publish the config file, right?) The 'scheme' index is given by a pure php function, not this library, which means PHP is having a problem parsing the CDN url you have specified.

**Comment by paatrick** [comment]
How should I specify my CDN_Url, do I need to pass my bucket? Or just need to inform https://s3.amazonaws.com?

**Comment by publiux** [comment]
You can just do https://s3.amazonaws.com . However, that's the default in the cdn.php config file. I'm not sure why it's not being parsed if you did in fact publish the cdn.php config file.

**Comment by paatrick** [comment]
We were able to resolve this by correctly correcting our cloud front address. And we left our CDN_Url by default https://s3.amazonaws.com. Anyway, thank you very much for your help and congratulations for the package.
