### ISSUE TITLE
Encountered a permanent redirect while requesting https://bucket-name.s3.eu-west-1.amazonaws.com/?encoding-type=url. Are you sure you are using the correct region for this bucket?

### ISSUE THREAD

**Issue by GZamfirSMB** [publiux/laravelcdn#26]
I'm sure my bucket region is 'eu-west-1'. I'm not sure why it says 'bucket-name' instead of the actual name of the bucket.

Any ideas?

**Comment by GZamfirSMB** [comment]
Sorry. My bad. I didn't modify the bucket name in the config.

**Comment by publiux** [comment]
No problem. Enjoy the package.
