### ISSUE TITLE
Cdn::mix and bypass=true results in double //

### ISSUE THREAD

**Issue by audunru** [publiux/laravelcdn#27]
I recently switch from Laravel Elixir to Mix, and noticed an issue with double slashes in my dev environment when I use Cdn::mix. I didn't have that problem before with Cdn::elixir

Since this is my dev environment Cdn's bypass option is true. So I'm trying to load assets locally.

The HTML with double slashes:

```
<link rel="stylesheet" href="http://localhost:8000//css/app.css">
<script src="http://localhost:8000//js/app.js"></script>
```

From default.blade.php

```
<link rel="stylesheet" href="{{ Cdn::mix('/css/app.css') }}">
<script src="{{ Cdn::mix('/js/app.js') }}"></script>
```

mix-manifest.json:

```
{
    "/js/app.js": "/js/app.js",
    "/css/app.css": "/css/app.css"
}
```

I looked at CdnFacade.php and the generateUrl() function. If I change

```
return Request::root().'/'.$path;
```

to

```
return Request::root().''.$path;
```

the double slash turns into a single slash, and my css and js loads again. But this might have other consequenses.

**Comment by publiux** [comment]
Instead of using {{ Cdn::mix('/css/app.css') }}, use {{ Cdn::mix('css/app.css') }}. Omit the initial forward slash.

**Comment by usurwool** [comment]
The same problem on local environment. Bypass option set in 'true'
Initial forward slash has omitted in layout.blade.php
```
<link rel="stylesheet" href="{{ CDN::mix('css/web.css') }}">
<script src="{{ CDN::mix('js/web/app.js') }}" defer></script>
```
mix-manifest.json:
```
{
    "/js/web/app.js": "/js/web/app.js",
    "/css/web.css": "/css/web.css"
}
```
The HTML has double slashes:
```
<link rel="stylesheet" href="http://localhost:8000//css/web.css">
<script src="http://localhost:8000//js/web/app.js" defer></script>
```
@publiux Could you please recheck this issue
