### ISSUE TITLE
upload folder in mix url

### ISSUE THREAD

**Issue by vigenb** [publiux/laravelcdn#29]
Hi there,
thanks for great repo.
when uploading files, it uploads to my prefered folder mentioned in AWS_CDN_ASSET_UPLOAD_FOLDER variable.
is it possible to use "AWS_CDN_ASSET_UPLOAD_FOLDER" folder when using Cdn::mix('some_file_path'). 
Cdn::mix always returns path without upload folder path.

Thanks in advance.

**Comment by publiux** [comment]
@vigenb This should be something you configure in your cloudfront distribution, not in the package configuration. With CloudFront, you can specify which folder in the bucket should serve the files, so there shouldn't be a need to return the upload folder path with mix().

**Comment by RishabSwift** [comment]
So what's the fix for this?
