### ISSUE TITLE
CDN not working as expected

### ISSUE THREAD

**Issue by vartanian** [publiux/laravelcdn#33]
Hi Guys,

Just want to start by saying that you've made a great package here!

So here is the issue, we are running on laravel 5.5/nginx, using AWS ELB and deploy via jenkins/AWS CodeDeploy, and during the build we run npm production and php artisan Cdn:push.

Everything was working as expected as of Friday which is when ran our last test of the week. We came in Monday, and we are suddenly not able pull from CD when our env=production. The files do indeed build and update on cdn so we know its not associated to S3, it appears to be package related.

We tested everything, looked over our code 10x, nothing stands out and all looks in place. However I did notice you guys made some commits, so I am wondering what may have changed and was it documented yet? 

We could really use your help resolving this before our deploy today, as we would hate to pull assets from our server if we can avoid it.

Thanks in advance!

Best,

-V

**Comment by vartanian** [comment]
Please note this is resolved, it was a syntax error on our side. 

Keep up the great work!

**Comment by vartanian** [comment]
Done

**Comment by publiux** [comment]
Good to hear. Let me know if there is anything you need.
