### ISSUE TITLE
Wrong paths on S3 after composer update

### ISSUE THREAD

**Issue by rishiyadav31** [publiux/laravelcdn#37]
Hello,

After updating composer, keys of files on S3 are wrong. It's taking absolute path instead of relative. i.e. instead of making **public** folder in my bucket as root folder, it's creating **var** as root folder. Full path of files are like /var/www/app/public/css/app.css instead of public/css/app.css.

Issue started happening after Symfony/finder got updated to 3.4.7 from 3.4.6.

After little debugging, I found that $file->getPathName() returns absolute path after updating.

**Comment by rishiyadav31** [comment]
Any update? we are still facing this issue.

**Comment by publiux** [comment]
Is this occurring when you are syncing objects to S3?

**Comment by rishiyadav31** [comment]
Yes. Whenever I do Cdn:push

**Comment by plicas** [comment]
@rishiyadav31 You still have this issue ?
