### ISSUE TITLE
Comparing local files and bucket..

### ISSUE THREAD

**Issue by diadal** [publiux/laravelcdn#39]
the same configuration work fine on Mac but never work in ubuntu 16.04

Comparing local files and bucket...

   Aws\Exception\CredentialsException  : Error retrieving credentials from the instance profile metadata server. (Client error: `GET http://169.254.169.254/latest/meta-data/iam/security-credentials/` resulted in a `404 Not Found` response:
not found
)

  at /var/www/html/gdf/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:88
    84|                 return (string) $response->getBody();
    85|             })->otherwise(function (array $reason) {
    86|                 $reason = $reason['exception'];
    87|                 $msg = $reason->getMessage();
  > 88|                 throw new CredentialsException(
    89|                     $this->createErrorMessage($msg)
    90|                 );
    91|             });
    92|     }

  Exception trace:

  1   Aws\Credentials\InstanceProfileProvider::Aws\Credentials\{closure}(Object(GuzzleHttp\Exception\ClientException))
      /var/www/html/gdf/vendor/guzzlehttp/promises/src/Promise.php:203

  2   GuzzleHttp\Promise\Promise::callHandler([Object(GuzzleHttp\Exception\ClientException), Object(GuzzleHttp\Psr7\Response)])
      /var/www/html/gdf/vendor/guzzlehttp/promises/src/Promise.php:156

  Please use the argument -v to see more details.

**Comment by cruex-de** [comment]
Aws\Exception\CredentialsException  : Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1000 milliseco
nds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))

  at D:\wamp\www\git\*\cms\vendor\aws\aws-sdk-php\src\Credentials\InstanceProfileProvider.php:88
    84|                 return (string) $response->getBody();
    85|             })->otherwise(function (array $reason) {
    86|                 $reason = $reason['exception'];
    87|                 $msg = $reason->getMessage();
  > 88|                 throw new CredentialsException(
    89|                     $this->createErrorMessage($msg)
    90|                 );
    91|             });
    92|     }

  Exception trace:

  1   Aws\Credentials\InstanceProfileProvider::Aws\Credentials\{closure}(Object(GuzzleHttp\Exception\ConnectException))
      D:\wamp\www\git\*\cms\vendor\guzzlehttp\promises\src\Promise.php:203

  2   GuzzleHttp\Promise\Promise::callHandler([Object(GuzzleHttp\Exception\ConnectException)])
      D:\wamp\www\git\*\cms\vendor\guzzlehttp\promises\src\Promise.php:156

  Please use the argument -v to see more details.

I think I have the same problem is there a fix?

**my problem maybe fixed this command: "php artisan config:clear" now its working.**

**Comment by PunchRockgroin** [comment]
This was a tricky one, but I've found that php artisan config:cache breaks the implementation because in laravelcdn/src/Publiux/laravelcdn/Providers/AwsS3Provider.php it's just using the S3Client without providing the 'credentials' key => value. When the config is cached, as far as I know the .env file is not loaded or whatever, as if you call env() after cache the values return null. 

So when I do config:cache, I make sure that I use the .aws/credentials file outlined in the docs below  [https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#credentials](url)

This way I can cache the config first, and then deploy assets after I've yarn build production
