### ISSUE TITLE
Embedding CSS/SCSS images has no /public/ in the link

### ISSUE THREAD

**Issue by cruex-de** [publiux/laravelcdn#41]
Hello,

I have a problem with embedding an image in CSS/SCSS, which should be on the CDN later, but after the compiling the /public/ is missing in the class when linking and therefore it cannot find it on the S3 server. Because the image is integrated as follows:

.flag-icon-en {
    background-image: url(/images/flags/4x3/en.svg);
}

but it should:

.flag-icon-en {
    background-image: url(/public/images/flags/4x3/en.svg);
}

Anybody got a fix? Because you can't just remove the "/public/" folder, so that the CDN is only /images/, /css/, /js/ as I saw it, is the Public folder hardgecoded correct?

**Comment by thanosalexander** [comment]
is there any update into this?

**Comment by cruex-de** [comment]
> is there any update into this?

Unfortunately not, I hope it's fixed soon.

I did it temporarily with hardlinks, like "https://cdn.xxxx.xx/public/images/flags/4x3/en.svg". But I hate that.

**Comment by thanosalexander** [comment]
yes it would be very helpfull as most of us use url() of images or fonts in our scss files..

**Comment by thanosalexander** [comment]
Solution found!

First, go to the web interface for your S3 bucket, click “Properties,” then “Permissions,” then “Edit CORS Configuration.” Enter this and save it:
```
<CORSConfiguration>
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
    </CORSRule>
</CORSConfiguration>
```

Next ,if you use Cloudfront to serve your files, go to the web interface for your Cloudfront “distribution,” and click “Distribution Settings,” then the “Behaviors” tab. Select the behavior (assuming you have only one) and click “Edit.”

For “Forward Headers,” change it from “None (Improves Caching)” to “Whitelist.” A “Whitelist Headers” section will appear. Add “Origin” to this list. This tells Cloudfront to take the “Origin” header into account when caching.

Thats it!

**Comment by cruex-de** [comment]
> Solution found!
> 
> First, go to the web interface for your S3 bucket, click “Properties,” then “Permissions,” then “Edit CORS Configuration.” Enter this and save it:
> 
> ```
> <CORSConfiguration>
>     <CORSRule>
>         <AllowedOrigin>*</AllowedOrigin>
>         <AllowedMethod>GET</AllowedMethod>
>     </CORSRule>
> </CORSConfiguration>
> ```
> Next ,if you use Cloudfront to serve your files, go to the web interface for your Cloudfront “distribution,” and click “Distribution Settings,” then the “Behaviors” tab. Select the behavior (assuming you have only one) and click “Edit.”
> 
> For “Forward Headers,” change it from “None (Improves Caching)” to “Whitelist.” A “Whitelist Headers” section will appear. Add “Origin” to this list. This tells Cloudfront to take the “Origin” header into account when caching.
> 
> Thats it!

fix this the missing "/public/" path for images on the app.css file?
I think that only fixes the problem of embedding external files/links?

**Comment by thanosalexander** [comment]
yes,, basically its a standard action we all of us have to do.. it has not to do with public..
eg now i use relative urls ```src: url('./fonts/Simple-Line-Icons.eot?v=2.4.0');``` and it is loading correctly.
From my point of view i wont say it is a bug but a missing documentation in Readme.
@publiux

**Comment by cruex-de** [comment]
Yeah? How does that work? Since the package laravelcdn loads the files into a /public/ folder, and this one is missing because it removes the image in the app.css "/images/flags/4x3/en.svg" and so the /public/ folder because it returns with the initial "/" to the initial structure of the domain?

**Comment by thanosalexander** [comment]
is this into a scss that you compile?
```background-image: url(/images/flags/4x3/en.svg);```
try this ```background-image: url(images/flags/4x3/en.svg);``` without slash

what error do you have on your console ?


PS ) My notice into the solution has not to do with ```public``` folder issue..
It has to do with the permissions of loading assets from cdn eg cloudfront via S3

**Comment by cruex-de** [comment]
Now i test it with this: background-image: url(images/flags/4x3/en.svg);

Webpack say: Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve './images/flags/4x3/en.svg' in 'D:\wamp\www\git\xxx\cms\resources\assets\sass'

he add "./" automatic

Folder structure of my resources folder:
/assets
/assets/images/flags/4x3/
/assets/sass/flags/flag-icon.scss

And when I use the ""../images/flags", all images are stored in the main folder of "images" and not in the folder "images/flags".

The only thing that worked so far where he didn't put the images in the main folder of images was "/../../images/flags", but then he saved the images in my app.css:

.flag-icon-en {
background image: url(/../../images/flags/4x3/en.svg);
}

**Comment by thanosalexander** [comment]
you cant remove public as its the folder that you have in included directories array inside config/cdn.php file...

**Comment by cruex-de** [comment]
> you cant remove public as its the folder that you have in included directories array inside config/cdn.php file...

And yet the image is only integrated with "https://cdn.xxx.xx/images/flags/4x3/en.svg" and not as "https://cdn.xxx.xx/public/images/flags/4x3/en.svg". How why?

i added to the webpack.mix.js this to the mix.sass:

.options({
        processCssUrls: false
    })
i think its working now but its not a got way...

**Comment by brentarcane** [comment]
Try using CDN::path() like this:

`{{ style(CDN::path('css/frontend.css')) }}`

See here - https://github.com/publiux/laravelcdn/blob/master/src/Publiux/laravelcdn/CdnFacade.php#L194

It generates URLs without the `public` path.
