### ISSUE TITLE
Cant run php artisan vendor:publish

### ISSUE THREAD

**Issue by paulocastellano** [publiux/laravelcdn#5]
Hi,

i am using laravel 5.2.2, i installed laravelcdn, but i when i run php artisan vendor:publish nothing happens, when i run php artisan cdn:push i have:

[Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "cdn" namespace.        

I looked at the Kernel.php and nothing has changed too.

**Comment by publiux** [comment]
Do you have the previous version, i.e. the Vinelab version, installed along with this one? It might be getting confused.

I just did a fresh install in Laravel 5.2.10 and it works fine. Have you updated your config/app.php file to include 'Publiux\laravelcdn\CdnServiceProvider::class,' in the providers array?

**Comment by paulocastellano** [comment]
I don't have old version from Vinelab and i set in app.php the provider :/

**Comment by publiux** [comment]
I just can't replicate this on a fresh install, or even my existing project. Can you post your providers array from app.php? Also, when you do 

``` php
php artisan
```

does any cdn command show up? For some reason, the provider seems to not be registering in your application. Also, have you tried dumping the composer autoload with

``` bash
composer dump-autoload
```

**Comment by paulocastellano** [comment]
Sorry bro, the problem was fix with composer dump-autoload, i forget this!

**Comment by publiux** [comment]
No worries. Glad it works. I am closing this issue.
