### ISSUE TITLE
Support for Laravel 5.8

### ISSUE THREAD

**Issue by nohumans** [publiux/laravelcdn#52]
Thanxx

**Comment by juhasev** [comment]
This would be nice and should be easy to do as there hasn't been major changes.

**Comment by juhasev** [comment]
Is this project still alive? If so it would be nice if you could merge the pull requests or maybe hand over the product to me and I will be happy to do code reviews / merge issues.

**Comment by nohumans** [comment]
Thanxx!

**Comment by juhasev** [comment]
@publiux Is not responding or has not been responding for a while. I went ahead and forked and published the fork with Laravel 5.8 compatibility.

[Laravel CDN](https://github.com/juhasev/laravelcdn)
