### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by keshansandeepa** [publiux/laravelcdn#69]
When i tried to php artisan cdn:push
Trying to access array offset on value of type null error  why is that ?

**Comment by MehediDracula** [comment]
+1

**Comment by jsznap** [comment]
same +1

**Comment by bikify** [comment]
same +1

**Comment by ruwad-co** [comment]
same +1

**Comment by publiux** [comment]
Should be fixed in v4.1.0

**Comment by kosta006** [comment]
I am still getting the same error on 4.1 unfortunately

**Comment by Webotvorba** [comment]
same here
