### ISSUE TITLE
laravel/framework 9 require symfony/finder ^6.0 

### ISSUE THREAD

**Issue by Chepa** [publiux/laravelcdn#72]

**Comment by igramnet** [comment]
Hello, how can I fix this?

`  
Problem 1
    - Root composer.json requires publiux/laravelcdn ~4.0 -> satisfiable by publiux/laravelcdn[v4.0.0].
    - publiux/laravelcdn v4.0.0 requires symfony/console ^5 -> found symfony/console[v5.0.0-BETA1, ..., 5.4.x-dev] but these were not loaded, likely because it conflicts with another require.

`

**Comment by dgillier** [comment]
Same here !

**Comment by publiux** [comment]
v.4.1.0 released which should solve this. Also implements support for L10.
